const CARGOS = ["PROFESIONAL SERVICIO SOCIAL OBLIGATORIO - MÉDICO","ENFERMERA","AUXILIAR ÁREA DE LA SALUD",
  "PROFESIONAL UNIVERSITARIO ÁREA SALUD - BACTERIÓLOGO","TÉCNICO EN SISTEMAS","ADMINISTRATIVO","OTRO"];
const DEPENDENCIAS_BASE = ["URGENCIAS CONSULTA Y PROCEDIMIENTOS","URGENCIAS OBSERVACIÓN",
  "HOSPITALIZACIÓN ESTANCIA GENERAL","APOYO DIAGNÓSTICO LABORATORIO CLÍNICO","QUIRÓFANOS","TALENTO HUMANO","FACTURACIÓN","GERENCIA"];
const TIPOS_VINCULACION = ["PLANTA PERMANENTE","PLANTA TEMPORAL","OPS","TERCERIZADO(A) / Contratista"];
const PERMISOS_LISTA = ["USUARIO DGH","CORREO INSTITUCIONAL","CARNET","INTRANET","SEVENET","MIPRES",
  "RUAF","VPN-TELECONSULTA","DESPRENDIBLES DE PAGO","NUBE FACTURACIÓN","TARJETA CON CHIP",
  "SISTEMA TURNOS Y RECARGOS","MIPRES HUDN","CENTRAL DE MEZCLAS","UTILIDADES FINANCIERAS","APLICATIVOS HUDN"];
const ENTRENAMIENTO_OPTS = ["DGH","CORREO INSTITUCIONAL","APLICATIVOS HUDN","INTRANET"];

export { CARGOS, DEPENDENCIAS_BASE, TIPOS_VINCULACION, PERMISOS_LISTA, ENTRENAMIENTO_OPTS };
